import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Karantina } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const karantina = Karantina({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-karantina",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Afacad:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${karantina.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
